name: Black (python)

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@40853de9f8ce2d6cfdc73c1b96f14e22ba44aec4  # v45.0.0
        with:
          files: "**/*.py"

      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install linters
        run: pip install black pylint

      - name: Black changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          black --check ${{ steps.changed-files.outputs.all_changed_files }}
